### PR TITLE
Fix errors to support Xcode

### PR DESCRIPTION
**Pull request by hallucino**
Hi,

this is a PR to be able to build with xcode on OSX.

### CODE REVIEW

**Comment by madmaxoft** [comment]
Shouldn't this PR be aimed at the upstream of the TCLAP project? I don't think we want any Cuberite-specific changes

**Comment by hallucino** [comment]
I don't know :) As you wish. It seems that Cuberite uses this fork for the compilation, no ?

**Comment by worktycho** [comment]
I think you should try and push upstream, and then see how they respond. We've had issues in the past, where we've had temporary changes on our repos.

**Comment by hallucino** [comment]
mc-server/tclap is sync with the upstream project ? Or even if I sent a patch to the upstream project, cuberite project will sync ?

**Comment by worktycho** [comment]
We sync when someone gets around to it, usually to fix a bug or to gain a feature. The polarssl repo shows what we're doing.

**Pull request closed without merging**
